export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_POST = 'FETCH_POST';
export const LIKE = 'LIKE';
export const COMMENT = 'COMMENT';
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';
export const FETCH_BY_CREATOR = 'FETCH_BY_CREATOR';
export const FETCH_BY_USERNAME = 'FETCH_BY_USERNAME';

export const CREATE_SERVICE = 'CREATE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const FETCH_ALL_SERVICE = 'FETCH_ALL_SERVICE';
export const FETCH_BY_SEARCH_SERVICE = 'FETCH_BY_SEARCH_SERVICE';
export const FETCH_SERVICE = 'FETCH_SERVICE';
export const LIKE_SERVICE = 'LIKE_SERVICE';
export const COMMENT_SERVICE = 'COMMENT_SERVICE';
export const END_LOADING_SERVICE = 'END_LOADING_SERVICE';
export const START_LOADING_SERVICE = 'START_LOADING_SERVICE';
export const FETCH_BY_CREATOR_SERVICE = 'FETCH_BY_CREATOR_SERVICE';
export const FETCH_BY_USERNAME_SERVICE = 'FETCH_BY_USERNAME_SERVICE';

export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const FETCH_ALL_ITEM = 'FETCH_ALL_ITEM';
export const FETCH_BY_SEARCH_ITEM = 'FETCH_BY_SEARCH_ITEM';
export const FETCH_POST_ITEM = 'FETCH_POST_ITEM';
export const LIKE_ITEM = 'LIKE_ITEM';
export const COMMENT_ITEM = 'COMMENT_ITEM';
export const END_LOADING_ITEM = 'END_LOADING_ITEM';
export const START_LOADING_ITEM = 'START_LOADING_ITEM';
export const FETCH_BY_CREATOR_ITEM = 'FETCH_BY_CREATOR_ITEM';
export const FETCH_BY_USERNAME_ITEM = 'FETCH_BY_USERNAME_ITEM';


export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
